# An Example Notebook to show you the basics

This is a "Markdown" cell. You can change the type of menu above. 

All of this is a "jupyter notebook". It contains explenatory text and fromulas in python. 

Below is a "code" cell that contains Python code that can be executed: Press the "Run" button from the menu or "alt-enter" to re-evaluate the code

In [4]:
17*2+8

42

In [6]:
for i in range(10):
    print(i," squared is",i*i)

0  squared is 0
1  squared is 1
2  squared is 4
3  squared is 9
4  squared is 16
5  squared is 25
6  squared is 36
7  squared is 49
8  squared is 64
9  squared is 81


In [14]:
x=3
y=4
z=x*y
z

12

## importing python modules

For heavy numeric compuation there is a python liberary called "numpy". We will import this library and give it the alias name "np":

In [9]:
import numpy as np

For heavy calculation we use vectors (a list of numbers) and matrices (an array of numbers). numpy can deal very well with such arrays. e.g. we use the np.random.rand function to create a 3 by 3 matrix of random numbers between 0 and 1:

In [16]:
np.random.rand(3,3)

array([[0.76367303, 0.12436833, 0.50857818],
       [0.14132382, 0.53232538, 0.97192192],
       [0.4193768 , 0.29565882, 0.37065351]])

of course we can also store these vectors and marices in a varaible. E.g. let us create a vector consisting of the numbers 0 to 9 and 10 by 10 matrix with all 1s:

In [22]:
v=np.arange(10)
A=np.ones((10,10))
A

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [23]:
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Variable names in python can be any string and it is also case sensitive. Here we will use Upper Case for a matrix and lower case for a vector. (But this is just a convention here). We can multiply a matrix with a vector

In [25]:
A*v

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

This might be not what you expected: Python tries something that is called "broadcast". It sees that our vector is length then and the matrix also has 10 as nn inner dimension. So it it multiplies every row with this vector. If we want the "real" multiplication of a matrix times a vector we need to use the "dot product":

In [27]:
A.dot(v)

array([45., 45., 45., 45., 45., 45., 45., 45., 45., 45.])

In [28]:
I=np.eye(10)
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

The "eye" matrix consisting only of diagonal elements of one will transform a vector onto itself. Instead of writing I.dot(v) we can also use the @ sign for the dot product: I @ v

In [29]:
I @ v

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

The dot product of a vector with itself is the length of the vector squared:

In [31]:
v.dot(v)

np.int64(285)

In [32]:
v @ v * 1.0

np.float64(285.0)